FROM public.ecr.aws/docker/library/python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY app ./app
COPY run_worker.py ./run_worker.py

RUN pip install --no-cache-dir boto3

CMD ["python", "run_worker.py"]